### ISSUE TITLE
help!!

### ISSUE THREAD

**Issue by hinata04** [Mob-Barley/noise_level_protocol#2] opened 2019-02-06 09:21 UTC
proc1 = float(proc1)

ValueError: could not convert string to float

can you help me?? thanks

**Comment by Mob-Barley** [comment] 2019-03-10 13:42
Hi hinata04,

I can't reproduce this error on my raspberry.
I need more information, what hard and software are you using?
Are you able to record a file with your microphone?

If yes, we can try some debugging, just add some print commands and lets see, what you get back.
Here is an example from line 31

```
os.system('clear')
        print(proc)
        time.sleep( 5 )
        proc1 = proc.strip()
        print(proc1)
        time.sleep( 5 )
        proc1 = float(proc1)
        print(proc1)
        time.sleep( 5 )
        proc_rms = proc_rms.strip()
        proc_rms = float(proc_rms)
````

You should see something like this

>      0.006425
> 0.006425
> 0.006425
> Measured values: 0.006425 / 0.001496 / 35.082931616706034 / 35.10994429940881 / 35
> 
> 14:37 No sound detected, delete: 20190310-143720.mp3

**Comment by grahamgelding** [comment] 2019-08-03 03:20
I got this error because sox had "no handler for file extension 'mp3'
fixed by:
sudo apt-get install libsox-fmt-mp3

**Comment by Mob-Barley** [comment] 2019-09-15 13:52
Thank you for the advice Graham,
I replaced sox with **libsox-fmt-mp3** under 'packages', I hope its more clearly now.
Also the plotly lib was wrong in my opinion, I replaced it with **Matplotlib**.

**Closed as completed** 2019-09-20 18:10 UTC
